export enum EnvironmentVariables {
    GCP_DIALOGFLOW_PROJECT_ID = 'GCP_DIALOGFLOW_PROJECT_ID',
    GCP_DIALOGFLOW_PRIVATE_KEY = 'GCP_DIALOGFLOW_PRIVATE_KEY',
    GCP_DIALOGFLOW_CLIENT_EMAIL = 'GCP_DIALOGFLOW_CLIENT_EMAIL',
    MAX_ITEMS_IN_MEMORY_STORAGE = 'MAX_ITEMS_IN_MEMORY_STORAGE'
}